name: Node CI

on:
  push:
    branches:
      - main  # Specify the branch you want to trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]  # Use LTS versions or the latest stable versions

    steps:
    - uses: actions/checkout@v3  # Update to the latest version
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3  # Update to the latest version
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies, build, and test
      run: |
        npm ci
        npm run build --if-present
        npm test
      env:
        CI: true
