name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # Update to the latest version
      - uses: actions/setup-node@v3  # Update to the latest version
        with:
          node-version: '18'  # Use a more recent Node.js version (LTS or stable)
      - run: npm ci
      - run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # Update to the latest version
      - uses: actions/setup-node@v3  # Update to the latest version
        with:
          node-version: '18'  # Use a more recent Node.js version (LTS or stable)
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}  # Ensure the secret is named correctly
